# Generated by Django 2.0.7 on 2018-09-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180925_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('0', '남'), ('1', '여')], default=1, help_text='※ 성별은 인게임 정보에 실제 반영됩니다. 신중히 선택해주세요.', max_length=2, verbose_name='성별'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='authnum',
            field=models.CharField(help_text='※ 인증번호 7자리는 게임 내에서 주민등록번호 뒷자리 대신 본인인증 용도로 사용됩니다. 기억하기 쉬운 7자리 숫자를 입력해주세요. 예: 1412927, 2236665, 1234567', max_length=7, verbose_name='인증번호'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='이메일'),
        ),
    ]
