# Generated by Django 2.0.7 on 2018-09-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180925_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(help_text='※ 성별은 인게임 정보에 실제 반영됩니다. 신중히 선택해주세요.', max_length=2, verbose_name='성별'),
        ),
    ]
