# Generated by Django 2.0.5 on 2018-09-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180912_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': '좋아요', 'verbose_name_plural': '좋아요'},
        ),
    ]
